on: push

test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
    - name: Run npm install
      run: npm install
    - name: Run tests
      uses: ospfranco/gh-jester@v1.0.13
      with:
        post-comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.JEST_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
